export const ADOPTION_EVENTS = Object.freeze({
  ONBOARDING_STARTED: 'onboarding_started',
  PHONE_SETUP_STARTED: 'phone_setup_started',
  PHONE_SETUP_COMPLETED: 'phone_setup_completed',
  FORWARDING_SETUP_STARTED: 'phone_forwarding_setup_started',
  FORWARDING_SETUP_COMPLETED: 'phone_forwarding_setup_completed',
  FORWARDING_TEST_PASSED: 'phone_forwarding_test_passed',
  FORWARDING_TEST_FAILED: 'phone_forwarding_test_failed',
  FIRST_SUCCESSFUL_AI_CALL: 'first_successful_ai_call',
  FIRST_HUMAN_TRANSFER: 'first_human_transfer',
  FIRST_MESSAGE_SENT: 'first_message_sent',
  FIRST_PUSH_RECEIVED: 'first_push_received',
  FIRST_BOOKING_COMPLETED: 'first_booking_completed',
  FIRST_LEAD_CAPTURED: 'first_lead_captured',
  BILINGUAL_CALL_COMPLETED: 'bilingual_call_completed',
  MOBILE_CONNECTED: 'mobile_connected',
  PUSH_ENABLED: 'push_enabled',
  ONBOARDING_ABANDONED: 'onboarding_abandoned',
});
